### ISSUE TITLE
keyerror：“score” 

### ISSUE THREAD

**Issue by xliang-L** [cyzhh/MMOS#1]
请问src.generate 的--source_file 参数的输入是tora模型的output吗？
我使用tora直接生成 的output 会有一个这样的报错显示没有score.
报错位置在src/create.py 的172行

**Comment by Zui-C** [comment]
score是推理答案正误的label，依靠它进行一轮过滤。用tora代码infer，其包含eval，在一步那时候产生。如果没有，可以自行比对答案加入就行。
