### ISSUE TITLE
Is the upper limit of reasoning paths decided by the generator models or the datasets?

### ISSUE THREAD

**Issue by yucc-leon** [cyzhh/MMOS#5]
K=9 seems meaningful, but do ToRA series models decide it, or the datasets?
Good work with novelty anyway!

**Comment by Zui-C** [comment]
> K=9 seems meaningful, but do ToRA series models decide it, or the datasets? Good work with novelty anyway!

Hi,
I personally understand that sampling around 9 paths is important in itself. The model and dataset affect whether you can sample enough paths. The dataset determines the upper limit of the paths that can be sampled, while the model determines efficiency (using Deepseek series sampling faster)

**Comment by yucc-leon** [comment]
> > K=9 seems meaningful, but do ToRA series models decide it, or the datasets? Good work with novelty anyway!
> 
> Hi, I personally understand that sampling around 9 paths is important in itself. The model and dataset affect whether you can sample enough paths. The dataset determines the upper limit of the paths that can be sampled, while the model determines efficiency (using Deepseek series sampling faster)

Clear and reasonable. Thanks!
