### ISSUE TITLE
Which code is used for Deduplication Algorithm? 

### ISSUE THREAD

**Issue by hanstong** [cyzhh/MMOS#6]
Hi, 
The dataset relys largely on the deduplication method, which code is used for the Deduplication Algorithm 1?
Thanks

**Comment by Zui-C** [comment]
> Hi, The dataset relys largely on the deduplication method, which code is used for the Deduplication Algorithm 1? Thanks

Hi,
The main part is in nodup.py.
Recommend referring to `generate.sh`, including: 1. combine the result  2. extract true cases 3. dedup
